export const DEFAULT_MOBILE_BREAKPOINT = 959
export const DEFAULT_LEFT_PANEL_WIDTH = 300
export const DEFAULT_LEFT_RAIL_WIDTH = 48
export const DEFAULT_RIGHT_PANEL_WIDTH = 320
export const DEFAULT_MOBILE_LEFT_PANEL_WIDTH = '66.67vw'
export const DEFAULT_MOBILE_RIGHT_PANEL_WIDTH = '100vw'
export const DEFAULT_CONTENT_MAX_WIDTH = 960
export const DEFAULT_TRANSITION_DURATION = '200ms'
