export const CONTENT_NAV_SELECTORS = {
  navLink: 'text=ContentNav Demo',
  pageTitle: '[data-testid="content-nav-page-title"]',
  availability: '[data-testid="content-nav-availability"]',
  toggleBubbleMode: '[data-testid="toggle-bubble-mode"]',
  toggleSingleTurnMode: '[data-testid="toggle-single-turn-mode"]',
  expandTriggerHover: '[data-testid="expand-trigger-hover"]',
  expandTriggerManual: '[data-testid="expand-trigger-manual"]',
  placementLeft: '[data-testid="placement-left"]',
  placementRight: '[data-testid="placement-right"]',
  externalQueryInput: '[data-testid="external-query-input"]',
  resetStateButton: '[data-testid="reset-content-nav-state"]',
  contentNavHost: '[data-testid="content-nav-host"]',
  contentNavRoot: '[data-testid="content-nav-overlay"]',
  contentNavOverlay: '[data-testid="content-nav-overlay"]',
  contentNavSearch: '[data-testid="content-nav-search"]',
  contentNavFallback: '[data-testid="content-nav-fallback"]',
  scrollContainer: '[data-testid="content-scroll-container"]',
  activeIdDisplay: '[data-testid="active-id-display"]',
  expandedDisplay: '[data-testid="expanded-display"]',
  queryDisplay: '[data-testid="query-display"]',
  placementDisplay: '[data-testid="placement-display"]',
  lastEventDisplay: '[data-testid="last-event-display"]',
  itemCountDisplay: '[data-testid="item-count-display"]',
} as const

export type ContentNavSelectors = typeof CONTENT_NAV_SELECTORS
